name: Build Java Project

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar con Maven
        run: mvn -B compile

      - name: Ejecutar tests
        run: mvn test

      # Opcional: Enviar gráfico de dependencias a GitHub (para dependabot)
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
