name: Build Java Project

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar y ejecutar tests con Maven
        env:
          JWT_SECRET: 12345678
        run: mvn -B clean verify -Dspring.profiles.active=test

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        
